Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports System.Windows.Forms

Namespace MapLesson3
    Partial Public Class Form1
        Inherits Form

        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Create a new DataSet
            Dim xmlDataSet As New System.Data.DataSet("XML DataSet")
            ' Load the XML document to the DataSet
            xmlDataSet.ReadXml("..\..\Data\rio2016.xml")
            ' This line of code is generated by Data Source Configuration Wizard
            pieChartDataAdapter1.DataSource = xmlDataSet.Tables("Table1")
        End Sub

        Private Sub OnDataLoaded(ByVal sender As Object, ByVal e As DevExpress.XtraMap.DataLoadedEventArgs) Handles vectorItemsLayer1.DataLoaded
            mapControl1.ZoomToFitLayerItems()
        End Sub
    End Class
End Namespace
